04:11:56 PM:DEBUG [logger_base.py:18] Mensaje a nivel debug
04:11:56 PM:INFO [logger_base.py:19] Mensaje a nivel info
04:11:56 PM:WARNING [logger_base.py:20] Mensaje a nivel watning
04:11:56 PM:ERROR [logger_base.py:21] mensaje a nivel error
04:11:56 PM:CRITICAL [logger_base.py:22] Mensaje a nivel critical
04:16:02 PM:DEBUG [Persona.py:53] 
            Id Persona: 1, 
            Nombre: Karolina, 
            Apellido: Mamani, 
            Email: cmama@mail.com
        
04:17:09 PM:DEBUG [Persona.py:53] 
            Id Persona: 1, 
            Nombre: Karolina, 
            Apellido: Mamani, 
            Email: cmama@mail.com
        
04:17:09 PM:DEBUG [Persona.py:55] 
            Id Persona: Jandet, 
            Nombre: OUTR, 
            Apellido: fkg@mail.com, 
            Email: None
        
04:17:44 PM:DEBUG [Persona.py:53] 
            Id Persona: 1, 
            Nombre: Karolina, 
            Apellido: Mamani, 
            Email: cmama@mail.com
        
04:17:44 PM:DEBUG [Persona.py:55] 
            Id Persona: None, 
            Nombre: Jandet, 
            Apellido: OUTR, 
            Email: fkg@mail.com
        
08:55:34 PM:ERROR [conexion.py:26] Ocurrio un error: invalid dsn: invalid connection option "dstabase"

08:57:27 PM:DEBUG [conexion.py:23] Conexion exitosa: <connection object at 0x0000021B05D82790; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5433', closed: 0>
08:58:45 PM:DEBUG [conexion.py:23] Conexion exitosa: <connection object at 0x00000175A2CE2790; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5433', closed: 0>
08:58:45 PM:ERROR [conexion.py:38] Ocurrio un error: 'NoneType' object has no attribute 'cursor'
09:01:03 PM:DEBUG [conexion.py:23] Conexion exitosa: <connection object at 0x000001C0E4492790; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5433', closed: 0>
09:01:03 PM:ERROR [conexion.py:38] Ocurrio un error: 'NoneType' object has no attribute 'cursor'
09:01:45 PM:DEBUG [conexion.py:23] Conexion exitosa: <connection object at 0x00000213E30A2790; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5433', closed: 0>
09:01:45 PM:DEBUG [conexion.py:35] Se abrio correctamente el cursor: <cursor object at 0x00000213E4DDF680; closed: 0>
